TrainerNames: ; 399ff (e:59ff)
	db "LAD@"
;	db "YOUNGSTER@"
	db "INSECTOPHILE@"
;	db "BUG CATCHER@"
	db "LASS@"
	db "SEAMAN@"
;	db "SAILOR@"
	db "JR.TRAINER♂@"
	db "JR.TRAINER♀@"
	db "ROCKET♀@"
;	db "POKéMANIAC@"
	db "NERDFIGHTER♂@"
;	db "SUPER NERD@"
	db "HIKER@"
	db "BIKER@"
	db "BURGLAR@"
	db "ELECTRICIAN@"
;	db "ENGINEER@"
	db "JUGGLER@"
	db "FISHER@"
	db "SWIMMER@"
	db "ROUGH NECK@"
;	db "CUE BALL@"
	db "GAMBLER@"
	db "NERDFIGHTER♀@"
;	db "BEAUTY@"
	db "PSYCHIC@"
	db "AC/DC FAN@"
;	db "ROCKER@"
	db "JUGGLER@"
	db "TAMER@"
	db "BIRD KEEPER@"
	db "BLACKBELT@"
	db "RIVAL1@"
	db "PROF.OAK@"
	db "CHIEF@"
	db "SCIENTIST@"
	db "GIOVANNI@"
	db "ROCKET♂@"
	db "COOLTRAINER♂@"
	db "COOLTRAINER♀@"
	db "BRUNO@"
	db "BROCK@"
	db "MISTY@"
	db "LT.SURGE@"
	db "ERIKA@"
	db "KOGA@"
	db "BLAINE@"
	db "SABRINA@"
	db "BUSINESS MAN@"
;	db "GENTLEMAN@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "LORELEI@"
	db "CHANNELER@"
	db "AGATHA@"
	db "LANCE@"
